data:
  Environmen:
  Test:
   URL: http://127.0.0.1:8080/
   user: 
   pwd: 
   adminUser: 
   adminPwd: 
  Online:
    URL: 
    user: 
    pwd: 
    adminUser:
    adminPwd:

db:
  host: 127.0.0.1
  port: 3306
  user: root
  passwd: '2018'
  charset: utf8

log:
  file_name: test.log
  backup: 5
  console_level: WARNING
  file_level: DEBUG
  pattern: '%(asctime)s - %(name)s -%(levelname)s - %(message)s'
