data:
  Environmen:
  Test:
   URL: 
   user: 
   pwd: 
   adminUser: 
   adminPwd: 
  Online:
    URL: 
    user: 
    pwd: 
    adminUser:
    adminPwd:

log:
  file_name: test.log
  backup: 5
  console_level: WARNING
  file_level: DEBUG
  pattern: '%(asctime)s - %(name)s -%(levelname)s - %(message)s'
